<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<StaticWebAssetBasePath>App_Plugins/Umbraco.Community.IconPicker</StaticWebAssetBasePath>
		<Description>Assets package for Umbraco.Community.IconPicker</Description>
		<RepositoryUrl>https://github.com/Ambertvu/Umbraco.Community.IconPicker</RepositoryUrl>
		<RootNamespace>Umbraco.Community.IconPicker.Assets</RootNamespace>
		<Version>17.1.4</Version>
	</PropertyGroup>

	<ItemGroup>
		<SupportedPlatform Include="browser" />
	</ItemGroup>
</Project>
